### ISSUE TITLE
非常感谢！

### ISSUE THREAD

**Issue by DigitalPlatform** [git-cloner/gitcache#1]
今天因为要在一台新机器上 clone 我自己的 repo，很多次都是报错中断，无奈之下在网上搜索解决办法，搜到了 gitclone.com 这个网站，感觉非常棒，速度飞快。以前也听说过不少朋友抱怨 clone 我那些 repo 很困难，这下好了，我可以向他们推荐 gitclone.com 了。

你们的工作很有意义。

**Comment by little51** [comment]
非常感谢您的认可和向朋友们的推荐，为开发者带来便利是gitclone.com的工作意义所在，是我们工作的动力。
