### ISSUE TITLE
vim plugin 使用镜像报503错误

### ISSUE THREAD

**Issue by digiprospector** [git-cloner/gitcache#10]
使用
git config --global url."https://gitclone.com/".insteadOf https://
这个方法

安装vim plugin的时候回报503错误
是不是并发太高了的原因?

**Comment by little51** [comment]
为了防止ddos攻击，gitclone.com对每10秒发起的git clone请求次数有限制，vim plugin安装时，可能会在短时间内clone比较小的github项目，这样会触发gitclone.com的限流策略，返回503

**Comment by digiprospector** [comment]
嗯,你们这个网站还是很好用的,谢谢

**Comment by little51** [comment]
谢谢😁
