### ISSUE TITLE
关于会员的建议

### ISSUE THREAD

**Issue by Chanlen** [git-cloner/gitcache#11]
建议搞一个终身会员.非常喜欢这个gitclone.com这个网站,希望能推出一个终身会员或者年会员

**Comment by little51** [comment]
非常感谢您的支持！gitclone.com的机制是首次浅克隆生成镜像，以后每日remote update镜像，以镜像为用户服务。从github.com的remote update并不是持续且稳定的，作者也在想各种办法，每个月和每个月的情况都不一样，所以在现阶段，还不能推出一个长期的会员机制，请见谅。
