### ISSUE TITLE
git clone -b报错fatal: Remote branch v0.9.1-release not found in upstream origin

### ISSUE THREAD

**Issue by sendaoYan** [git-cloner/gitcache#19]
```bash
git clone -b v0.9.1-release https://gitclone.com/github.com/adoptium/aqa-tests.git
git clone -b v0.9.1-release https://github.com/adoptium/aqa-tests.git
```

![image](https://user-images.githubusercontent.com/24123821/176391929-5e2f8bb9-b745-4180-9c15-c8d240460aea.png)

**Comment by little51** [comment]
gitcache不支持分支和递归。因为gitcache建立缓存时，是按main或master镜像的。

**Comment by sendaoYan** [comment]
> gitcache不支持分支和递归。因为gitcache建立缓存时，是按main或master镜像的。

好吧

**Comment by little51** [comment]
gitcache目前已支持branch了
