### ISSUE TITLE
recursive 情况慢的问题

### ISSUE THREAD

**Issue by JollyJiang** [git-cloner/gitcache#2]
如题

**Comment by little51** [comment]
因为gitclone.com使用了http中转下载的方式，对于主项目，通过在url中嵌入gitclone.com的办法将clone请求重定向到gitclone.com。但recursive子项目还是指向github.com，所以会慢，主项目clone完成后，有个 .gitmodules隐藏文件，将里面的url逐个嵌入gitclone.com解决，不然只能采用全局代理，这个gitclone.com解决不了。
