### ISSUE TITLE
能否启用支持默认clone所有分支

### ISSUE THREAD

**Issue by mawanglin** [git-cloner/gitcache#20]
默认使用gitclone.com进行加速时，只会clone主分支，这样其实很不方便，切换每个分支是都需要手动操作，可否像ghproxy.com网站那样，默认加速时不带分支参数即可clone所有分支到本地，谢谢。

**Comment by little51** [comment]
gitclone.com缓存的原理是拦截git命令的http请求，如果命中缓存，则直接从缓存返，如果未命中，重定向到github.com，然后延时建立缓存。如果支持分支，需要改动http请求拦截的代码，最麻烦是还是缓存的目录结构可能要调整，我看以前也有网友提出过此需求，我考虑最近增加这一特性，clone所有分支速度太慢，遍历难度大，初步考虑先支持-b参数

**Comment by mawanglin** [comment]
> gitclone.com缓存的原理是拦截git命令的http请求，如果命中缓存，则直接从缓存返，如果未命中，重定向到github.com，然后延时建立缓存。如果支持分支，需要改动http请求拦截的代码，最麻烦是还是缓存的目录结构可能要调整，我看以前也有网友提出过此需求，我考虑最近增加这一特性，clone所有分支速度太慢，遍历难度大，初步考虑先支持-b参数

好的，期待新特性上线，辛苦
![0A8678BA](https://user-images.githubusercontent.com/3214028/179913259-6a05d216-110f-40b5-9664-76098a968b2d.gif)

**Comment by little51** [comment]
git clone 的http请求原理是先发一次get info/refs取到所有分支列表，然后发post git-upload-pack，目前如果之前无缓存，clone请求会重定向到github.com，是支持-b参数的，但如果有缓存的情况下，我就得解析一下post的报文，查明clone的是哪个分支。

**Comment by little51** [comment]
目前的实现有点小问题，在git发get请求时，我就开始建本地镜像（main分支缓存），但这个时候并不知道git要clone具体哪个分支，有点抢跑的意思，不过在post时，还有一个mirror环节

**Comment by little51** [comment]
对git clone mirror测试时发现，git clone mirror虽然只是建立的主分支的镜像，但随后的git remote update对镜像的更新，会同步所有分支到镜像。所以对gitcache进行了微调，mirror后立即remote update，这样就可以支持git clone -b 分支了
