### ISSUE TITLE
支持commit,push吗，还是只支持clone

### ISSUE THREAD

**Issue by huanghe-1** [git-cloner/gitcache#21]

**Comment by little51** [comment]
只支持clone。不过有变通的办法，就是用gitclone.com拉取的代码，修改.git/config里的url为原始github.com，就可以commit和push了

**Comment by huanghe-1** [comment]
可以在香港弄个服务器做中转加速服务是王道，这样commit,push都支持了，私有项目也支持，只做clone镜像太占硬盘空间资源了，收的vip费不够买服务器的。
