### ISSUE TITLE
支持私有项目吗？

### ISSUE THREAD

**Issue by huanghe-1** [git-cloner/gitcache#22]

**Comment by little51** [comment]
不支持，私有项目无法镜像（git clone mirror）

**Comment by huanghe-1** [comment]
之所以有镜像的需求，主要是因为墙的干扰，导致不能正常的访问，gitcache在缓存镜像的时候，是怎么解决墙干扰的问题啊？如果已经解决了，那可以把网络链路打通，给vip商业客户做直连功能(非缓存镜像)，这样就能支持私有项目了。

**Comment by little51** [comment]
1、首次clone（未建立起镜像）的情况下，客户端的请求是直接redirect到github.com的，这就有可能会不通，clone会失败，但gitcache会异步起一个从github.com的ssh类型mirror、depth=1的请求建立镜像，在很短时间内就会完成镜像，从于客户端来看，clone报错，过一小会儿再clone会很快 2、如果有镜像，会直接从镜像取 3、每天同步一次镜像。ssh链接是稳定的，不会时通时断！所以不用gitclone.com，直接用ssh也是可以的，但速度会慢些

**Comment by huanghe-1** [comment]
大佬辛苦

**Comment by huanghe-1** [comment]
明白了，是把失败提前放在服务器端换取客户端的一次成功率，正常clone时，因为墙干扰的原因，10次可能成功那么一次，但速度还是挺快的，遇到这种情况，我就不断的重试，直到成功为止，心挺累的。每天同步镜像，应该一次成功率不高吧，还得多次同步，只是对于客户端来说一次成功了。

**Comment by little51** [comment]
每天同步镜像，用的是ssh方式（默认的https成功率极低），成功率100%，至少目前是这样

**Comment by huanghe-1** [comment]
多谢，难怪经常连接不上，我用的https，我也用ssh试试
