### ISSUE TITLE
有全球cdn吗，为什么会有那么多海外用户

### ISSUE THREAD

**Issue by huanghe-1** [git-cloner/gitcache#23]
看了下官网24小时数据，有很多海外用户，按说github本身有全球cdn，只是大陆"政府网"导致有镜像需求，海外直连很快的，难道gitcache是分布式架构，又包了一层镜像缓存的cdn？
可能是我认知水平吧，没有想明白。

**Comment by little51** [comment]
没有CDN之类的，gitclone.com主要访问者是在国内，海外也有一些用户，比国内要少很多，在首页将鼠标移到黄点上可以看出来访问次数，kibana可能在显示上有点问题。此外，gitclone.com也为classnotfound.com.cn导流，在bing上搜git clone或git clone speed等关键字gitclone.com排名比较靠前也是网站海外访问量大的一个因素
