### ISSUE TITLE
克隆分支和更新子工程的时候会出错

### ISSUE THREAD

**Issue by C1009919253** [git-cloner/gitcache#24]
$ git clone --branch ros2 --recursive https://github.com/XXX
正克隆到 'XXX'...
fatal: 远程分支 ros2 在上游 origin 未发现

$ git submodule update 
remote: 枚举对象中: 1160, 完成.
remote: 对象计数中: 100% (1160/1160), 完成.
remote: 压缩对象中: 100% (936/936), 完成.
remote: 总共 1160（差异 169），复用 1160（差异 169），包复用 0
接收对象中: 100% (1160/1160), 6.32 MiB | 298.00 KiB/s, 完成.
处理 delta 中: 100% (169/169), 完成.
error: Could not read 79aead2deafe0f9c5134422566c2f80e2db96613
fatal: Failed to traverse parents of commit 46f497a1ef058750f59277c88578f9f2c13ea670
error: https://gitclone.com/github.com/XXX 未发送所有必需的对象

无法在子模组路径 'XXX' 中获取，尝试直接获取 b448553725634aa83d25b356a7de12ba61647377：
error: 服务器不允许请求未公开的对象 b448553725634aa83d25b356a7de12ba61647377
获取了子模组路径 'XXX'，但是它没有包含 b448553725634aa83d25b356a7de12ba61647377。直接获取该提交失败。

**Comment by little51** [comment]
请将项目名发送到gitclone@126.com，我删除镜像重建一下再试，另外，gitclone.com不支持递归clone
