### ISSUE TITLE
仓库403

### ISSUE THREAD

**Issue by chenxuan520** [git-cloner/gitcache#25]
无法克隆项目，ycm和coc之类都不行
$ git version
git version 2.33.1

fatal: unable to access 'https://gitclone.com/github.com/neoclide/coc.nvim/': The requested URL returned error: 403

**Comment by little51** [comment]
blacklist处理中，对空串的判断有问题，已修复。
https://github.com/git-cloner/gitcache/commit/e0d6da38c6562b5ca92486d558ab58566753925a
