### ISSUE TITLE
最近缓存滞后了 gitclone出现差异。克隆的速度也只有200KB了

### ISSUE THREAD

**Issue by jhsvip** [git-cloner/gitcache#3]
啥情况？服务器出问题了？

**Comment by little51** [comment]
最近由于4台缓存服务器硬盘基本用尽，又增加了一台，5台并发执行git remote update，github.com会返回429（并发数过多）的异常，所以进行了错峰更新，但都保证了一天一同步。克隆速度问题，刚测试发现是防火墙策略的问题，已修正，多谢。

**Comment by jhsvip** [comment]
> 最近由于4台缓存服务器硬盘基本用尽，又增加了一台，5台并发执行git remote update，github.com会返回429（并发数过多）的异常，所以进行了错峰更新，但都保证了一天一同步。克隆速度问题，刚测试发现是防火墙策略的问题，已修正，多谢。

感谢大佬回复！
