### ISSUE TITLE
gitclone的时候还是有差异，速度上去了，请大佬看看哪儿的问题

### ISSUE THREAD

**Issue by jhsvip** [git-cloner/gitcache#4]
![image](https://user-images.githubusercontent.com/63874546/91592080-8c804380-e990-11ea-9403-62de5c087179.png)

![image](https://user-images.githubusercontent.com/63874546/91592935-db7aa880-e991-11ea-8c26-6bcbc9bb736d.png)

目前依然存在差异 克隆的都是几天前的东西了 服务器缓存应该是木有更新

**Comment by little51** [comment]
我对这个镜像手工执行了git remote update，发现镜像是最新的，clone到本地看，最后一次commit的是b8eb26fadc827d1df8f4e5ab8c9216c5098e8318，与github.com里11天前最后的提交是一致的，您看具体是哪个文件，我对比测试一下，如果的确是有差异，我把这个镜像重建一下试试，非常感谢。

**Comment by little51** [comment]
另外，您看把本地的.git/config里的url 改成原始值： https://github.com/acidanthera/Lilu ，然后 git pull，看是否会拉下来新文件。clone时显示的差异、复用对应delta、 reused，可能是显示上的问题。如果镜像与github.com的确有差异，我怀疑与git版本有关系，新上线的第5台与前4台git小版本略有不同，这个镜像正好落到了第5台机器上，我再排查一下。

**Comment by jhsvip** [comment]
> 另外，您看把本地的.git/config里的url 改成原始值： https://github.com/acidanthera/Lilu ，然后 git pull，看是否会拉下来新文件。clone时显示的差异、复用对应delta、 reused，可能是显示上的问题。如果镜像与github.com的确有差异，我怀疑与git版本有关系，新上线的第5台与前4台git小版本略有不同，这个镜像正好落到了第5台机器上，我再排查一下。

改原始值克隆不动。。。5K/S。 我现在克隆到gitee 然后再从gitee克隆到本地没有问题 大佬您再排查一下，另外克隆opencore等都会出现差异 如果是11天前的 那应该不太对 更新了都4～5天了 缓存还没有更新

**Comment by little51** [comment]
我把这两个镜像删除掉了，您有空验证一下，如果没问题，则可能是我这台机器上的git版本造成的。

**Comment by jhsvip** [comment]
> 我把这两个镜像删除掉了，您有空验证一下，如果没问题，则可能是我这台机器上的git版本造成的。

不行大佬 还是老样子。。。悲催
![E89B11D9-AB41-471D-8188-F0D14F8F2EBB](https://user-images.githubusercontent.com/63874546/92137967-65b68700-ee40-11ea-852f-20b2b0b02fcb.png)

**Comment by little51** [comment]
是 https://github.com/acidanthera/Lilu这个项目吧？看有哪个文件最近改过？我试一下clone下来是不是新的。我上次看的readme.md，是最新的

**Comment by jhsvip** [comment]
对 是这个项目 我刚刚又克隆了一遍 还是老样子。。。不仅仅lilu包括 https://github.com/acidanthera 它基本上全家都不行。。。
![0E6EB66F-0F95-49C3-856E-CBFDE7F18F15](https://user-images.githubusercontent.com/63874546/92258914-a3cbad80-ef09-11ea-8cda-a1e18be5efde.png)

附上我用的编译kexts的脚本 大佬看看
[归档.zip](https://github.com/git-cloner/gitcache/files/5175791/default.zip)

**Comment by little51** [comment]
git clone时显示的差异（delta ）是因为git存储版本历史的增量机制，不是指当前clone的版本与github.com的主分支之间的差异。会不会是字面上的误解，还是的确的有的文件内容与github.com里主分支的不同？ 关于delta,请参见： https://stackoverflow.com/questions/57991448/in-git-what-does-delta-mean#:~:text=Git%20uses%20Delta%20encoding%20which%20indicates%20a%20way,You%20can%20read%20more%20here%20for%20better%20understanding.

**Comment by jhsvip** [comment]
感谢大佬回复 我对比了下编译完成的文件 是相同的 应该不影响的！再次感谢！
