### ISSUE TITLE
问下缓存的更新的机制是怎样的？

### ISSUE THREAD

**Issue by cui2121** [git-cloner/gitcache#5]
自己搭建了个gitcache给内网用户缓存加速，现发现github上代码更新了，但是缓存里文件还是旧的，已经持续24小时了

**Comment by little51** [comment]
镜像的建立是用 git clone --depth=1 --mirror github库的url  本地目录，这里边的技巧是用depth=1，用浅克隆快速建立镜像；更新缓存的机制是：用cron定时任务枚举所有镜像目录，逐个执行git -C 本地目录 remote update。这个命令会更新镜像，自动回收一些文件（git的gc）

**Comment by little51** [comment]
由于github.com对并发的请求数有限制，所以gitclone.com按IP错峰更新，如果你只有一台机器，就直接在cron里调就行了，不要判断IP。我看gitrepo.go里go SyncLocalMirrorFromRemote()默认是早上4点执行，你把这段改成合适的时间点即可。

**Comment by cui2121** [comment]
> 镜像的建立是用 git clone --depth=1 --mirror github库的url 本地目录，这里边的技巧是用depth=1，用浅克隆快速建立镜像；更新缓存的机制是：用cron定时任务枚举所有镜像目录，逐个执行git -C 本地目录 remote update。这个命令会更新镜像，自动回收一些文件（git的gc）

好的，明白了。谢谢

**Comment by cui2121** [comment]
> 由于github.com对并发的请求数有限制，所以gitclone.com按IP错峰更新，如果你只有一台机器，就直接在cron里调就行了，不要判断IP。我看gitrepo.go里go SyncLocalMirrorFromRemote()默认是早上4点执行，你把这段改成合适的时间点即可。

ok，明白了，谢谢
