### ISSUE TITLE
fatal: Remote branch **** not found in upstream origin

### ISSUE THREAD

**Issue by cui2121** [git-cloner/gitcache#6]
自己搭建了个gitcache给内网的git clone加速，git clone -b *** 下载带分支的仓库时报错：fatal: Remote branch **** not found in upstream origin。

**Comment by little51** [comment]
gitcache未实现对branch的clone。请将git clone命令发送到gitclone@126.com，我调试一下gitcache。

**Comment by cui2121** [comment]
> gitcache未实现对branch的clone。请将git clone命令发送到[gitclone@126.com](mailto:gitclone@126.com)，我调试一下gitcache。

邮件已经发给你了。顺便问下，你们有打算支持对branch的clone吗？

**Comment by little51** [comment]
给您回邮件了，主要受限于原来规划的mirror目录的结构问题，支持branch改动比较大，暂无开发计划。

**Comment by cui2121** [comment]
收到了，谢谢
