### ISSUE TITLE
warning: You appear to have cloned an empty repository.

### ISSUE THREAD

**Issue by UndisclosedDev** [git-cloner/gitcache#7]
When trying to clone any repository, always throw away this error.
**warning: You appear to have cloned an empty repository.**

The repository is cloned in the local folder, but not in /var/gitcache

If I try to clone into another folder, nothing is cloned, the new folder is created, but it is empty and the same error
**warning: You appear to have cloned an empty repository.**
 
LOG: 2020/11/04 16:50:49 gitcache.go:400: git clone from remote : https://github.com/tendermint/tendermint.git /var/gitcache/github.com/tendermint/tendermint.git
LOG: 2020/11/04 16:50:49 dbservice.go:93: Stats : redirect
LOG: 2020/11/04 16:50:59 gitcache.go:160: valid local cache! .git path not exists
LOG: 2020/11/04 16:50:59 gitcache.go:61: execute local git command : git,[clone --depth=1 --mirror --progress https://github.com/tendermint/tendermint.git /var/gitcache/github.com/tendermint/tendermint.git]
Cloning into bare repository '/var/gitcache/github.com/tendermint/tendermint.git'...
LOG: 2020/11/04 16:50:59 gitcache.go:346: client send git request: 172.26.27.130:45480 GET /github.com/tendermint/tendermint.git/info/refs HTTP/1.1
LOG: 2020/11/04 16:50:59 gitcache.go:348: git params: {Repository:github.com/tendermint/tendermint.git Gitservice:git-upload-pack IsInfoReq:true}
LOG: 2020/11/04 16:50:59 gitcache.go:350: client send git request: GET true valid ok
LOG: 2020/11/04 16:50:59 gitcache.go:61: execute local git command : git,[-C /var/gitcache/github.com/tendermint/tendermint.git remote]
origin
LOG: 2020/11/04 16:50:59 gitcache.go:186: execute local git command : git-upload-pack,[--stateless-rpc --advertise-refs /var/gitcache/github.com/tendermint/tendermint.git]
**_warning: You appear to have cloned an empty repository._**
LOG: 2020/11/04 16:51:09 gitrepo.go:192: broadcast git clone command to chain : https://github.com/tendermint/tendermint.git

**Comment by little51** [comment]
After the execution is complete,please check whether a mirror file is generated in /var/gitcache. If it is not generated, the possible situation is that the current user does not have read and write permissions to /var/gitcache
Method 1: Use sudo chmod to authorize /var/gitcache
Method 2: Specify a directory with read and write permissions at startup, such as ./gitcache -b /home/yourusername/gitcache

**Comment by UndisclosedDev** [comment]
In the tendermint clone example, I can see that folders and some files are created. I presume that the permissions are fine.

What I don't see are only the files with the source code, they are not copied. I think that could be the problem.
The user has write, read and execute authorization in the _/var/gitcache_ folder

I attach path and list of folders and files created

TREE
/var/gitcache/github.com/tendermint/tendermint.git
.
├── [drwxrwxr-x]  branches
├── [-rw-rw-r--]  config
├── [-rw-rw-r--]  description
├── [-rw-rw-r--]  FETCH_HEAD
├── [-rw-rw-r--]  HEAD
├── [drwxrwxr-x]  hooks
│   ├── [-rwxrwxr-x]  applypatch-msg.sample
│   ├── [-rwxrwxr-x]  commit-msg.sample
│   ├── [-rwxrwxr-x]  fsmonitor-watchman.sample
│   ├── [-rwxrwxr-x]  post-update.sample
│   ├── [-rwxrwxr-x]  pre-applypatch.sample
│   ├── [-rwxrwxr-x]  pre-commit.sample
│   ├── [-rwxrwxr-x]  pre-merge-commit.sample
│   ├── [-rwxrwxr-x]  prepare-commit-msg.sample
│   ├── [-rwxrwxr-x]  pre-push.sample
│   ├── [-rwxrwxr-x]  pre-rebase.sample
│   ├── [-rwxrwxr-x]  pre-receive.sample
│   └── [-rwxrwxr-x]  update.sample
├── [drwxrwxr-x]  info
│   └── [-rw-rw-r--]  exclude
├── [drwxrwxr-x]  objects
│   ├── [drwxrwxr-x]  info
│   └── [drwxrwxr-x]  pack
└── [drwxrwxr-x]  refs
    ├── [drwxrwxr-x]  heads
    └── [drwxrwxr-x]  tags

**Comment by little51** [comment]
What is the version of your git(git --version)? Maybe it's because your git version is below 2.0? Such as centos' default git version is 1.8,I compared mirror of gitclone and found that there were no shallow and packed-refs file.If git version below 2.0,try update git and remove mirror,retry. If that's not this reason, I'll do another test.

**Comment by UndisclosedDev** [comment]
CentOS Linux release 7.8.2003 (Core)
-----
git --version
git version 2.24.3

**Comment by UndisclosedDev** [comment]
I created the database by analyzing the source code.
There are no instructions or script to create the database and tables.

Could the database, missing tables or fields create such problems?

### My Tables
**gitcache_stats**
id
stat_class
stime
cachehit
redirect
visit
vipvisit
search
imagetest

**gitcache_repos**
id
startcount
hitcount
ctime
utime
last_recommendtime
updated_at
name
language
path
description

**Comment by little51** [comment]
try use git command direct:
`git clone --depth=1 --mirror --progress https://github.com/tendermint/tendermint.git var/gitcache/github.com/tendermint/tendermint.git`
and check  if  shallow and packed-refs exists
It is not related to the database,The database is not necessary.the sql script is 
CREATE TABLE `gitcache_repos` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL DEFAULT '',
  `path` varchar(255) NOT NULL DEFAULT '',
  `ctime` timestamp NULL DEFAULT NULL,
  `utime` timestamp NULL DEFAULT NULL,
  `hitcount` int(11) DEFAULT '0',
  `tcount` int(11) NOT NULL DEFAULT '10',
  `starcount` int(11) DEFAULT '0',
  `language` varchar(20) DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `owner` bigint(20) DEFAULT NULL,
  `description` varchar(1000) DEFAULT NULL,
  `last_recommendtime` bigint(20) DEFAULT '0',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `idx_gitcache_repos` (`path`),
  KEY `idx_gitcache_repos1` (`name`),
  KEY `idx_gitcache_repos_l` (`last_recommendtime`)
) ENGINE=InnoDB AUTO_INCREMENT=24920 DEFAULT CHARSET=utf8mb4;

**Comment by little51** [comment]
I find out the problem. if you clone first time,the mirror is not exists,then redirect to github.com,so clone the repo to you current folder,If you try to clone into another folder,**git mirror is in progress(dealy 10 Second)**,so report warning: You appear to have cloned an empty repository.
waiting mirror progress complate the clone from mirror is ok.

**Comment by UndisclosedDev** [comment]
If I clone directly using the git command
**git clone --depth=1 --mirror --progress https://github.com/tendermint/tendermint.git /var/gitcache/github.com/tendermint/tendermint.git**

all files and folders are copied correctly, including:

- shallow 
- packed-refs

If I use gitcache those 2 files are not created, they don't exist.
The other folders are created but empty. They do not contain any files
```
/var/gitcache/github.com/tendermint
└── tendermint.git
    ├── branches
    ├── config
    ├── description
    ├── FETCH_HEAD
    ├── HEAD
    ├── hooks
    │   ├── applypatch-msg.sample
    │   ├── commit-msg.sample
    │   ├── fsmonitor-watchman.sample
    │   ├── post-update.sample
    │   ├── pre-applypatch.sample
    │   ├── pre-commit.sample
    │   ├── pre-merge-commit.sample
    │   ├── prepare-commit-msg.sample
    │   ├── pre-push.sample
    │   ├── pre-rebase.sample
    │   ├── pre-receive.sample
    │   └── update.sample
    ├── info
    │   └── exclude
    ├── objects
    │   ├── info
    │   └── pack
    └── refs
        ├── heads
        └── tags
```

**Comment by little51** [comment]
in gitcache.go the 95 line,
`return execShell("git", []string{"clone", "--depth=1", "--mirror", "--progress", remote, local})`
before this line,add fmt.Print,check remote and local variable,add check git command log what happened,what diff between gitcache and clone directly.

**Comment by UndisclosedDev** [comment]
I already fixed the problem.
Because CentOS originally has version 1.18 installed, I installed a newer version from iusrepo/git224

I uninstalled that version from iusrepo/git224, and installed the same version from End Point repo.

Gitcache worked as expected.

Thanks for your help

**Comment by UndisclosedDev** [comment]
Can you post the script for table **gitcache_stats**?

**Comment by little51** [comment]
CREATE TABLE `gitcache_stats` (
  `Id` int(11) NOT NULL AUTO_INCREMENT,
  `stime` timestamp NULL DEFAULT NULL,
  `cachehit` decimal(10,0) DEFAULT '0',
  `redirect` decimal(10,0) DEFAULT '0',
  `visit` decimal(10,0) DEFAULT '0',
  `vipvisit` decimal(10,0) DEFAULT '0',
  `search` decimal(10,0) DEFAULT '0',
  `imagetest` decimal(10,0) DEFAULT '0',
  `githubapp` decimal(10,0) DEFAULT '0',
  `githubdesktop` decimal(10,0) DEFAULT '0',
  `githubcli` decimal(10,0) DEFAULT '0',
  `gitexe` decimal(10,0) DEFAULT '0',
  PRIMARY KEY (`Id`),
  UNIQUE KEY `inx_stats_time` (`stime`)
) ENGINE=InnoDB AUTO_INCREMENT=91 DEFAULT CHARSET=utf8mb4;

**Comment by little51** [comment]
if you use database,please add environment variables: 
MYSQL_DSN
the value is : username:password@tcp(mysqlip:3306)/databasename
such as : root:root@tcp(127.0.0.1:3306)/gitcache
