### ISSUE TITLE
设置git参数有些问题，需要如下修改，建议网站修改下。

### ISSUE THREAD

**Issue by yueswing07** [git-cloner/gitcache#8]
git config --global url."https://gitclone.com/github.com/".insteadOf https://github.com/

**Comment by little51** [comment]
​git config --global url."https://gitclone.com/".insteadOf https:// 与 git config --global url."https://gitclone.com/github.com/".insteadOf https://github.com/执行的结果是等效的

**Comment by yueswing07** [comment]
@little51   效果一样只是针对 github    如果是其他的 比如 https://gitee.com 等也会影响啊
